edit component
Geode-solutions/GeodeApp pull request #19
Opened 2024-07-17 12:38 UTC by SpliiT

2024-07-17 13:12 UTC, JulienChampagnol approved these changes

2024-07-17 13:35 UTC, BotellaA requested changes

2024-07-17 13:35 UTC, BotellaA commented on components/SideBar.vue
> +    <div>
j'aime pas du tout ces div en plus...

2024-07-17 13:35 UTC, BotellaA commented on components/SideBar.vue
> +  setup() {
non, utilise script setup

2024-07-17 13:53 UTC, BotellaA approved these changes

2024-07-18 08:15 UTC, BotellaA approved these changes

2024-07-18 08:15 UTC, BotellaA commented on components/SideBar.vue
> +    id: 1,
Can you remove all the id

2024-07-18 09:44 UTC, merged

2024-08-26 11:57 UTC, JulienChampagnol commented
:tada: This PR is included in version 0.2.0-rc.1 :tada:

The release is available on [GitHub release](https://github.com/Geode-solutions/GeodeApp/releases/tag/v0.2.0-rc.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-09-02 13:28 UTC, JulienChampagnol commented
:tada: This PR is included in version 0.2.0 :tada:

The release is available on [GitHub release](https://github.com/Geode-solutions/GeodeApp/releases/tag/v0.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: